/**
 * Offline fallback catalog when FatSecret is unavailable (e.g. Vercel egress IP
 * not allowlisted). Kept in sync with ensureSeedFoods in foods/search route.
 */
export const foodSeeds = [
  { name: "Chicken Breast", brand: "Generic", servingSize: "100g", calories: 165, protein: 31, carbs: 0, fats: 3.6 },
  { name: "Chicken Thigh", brand: "Generic", servingSize: "100g", calories: 209, protein: 26, carbs: 0, fats: 11 },
  { name: "Ground Turkey", brand: "Generic", servingSize: "100g", calories: 189, protein: 27, carbs: 0, fats: 8 },
  { name: "Egg", brand: "Generic", servingSize: "1 large", calories: 78, protein: 6.3, carbs: 0.6, fats: 5.3 },
  { name: "Egg Whites", brand: "Generic", servingSize: "100g", calories: 52, protein: 11, carbs: 0.7, fats: 0.2 },
  { name: "Salmon Fillet", brand: "Generic", servingSize: "100g", calories: 208, protein: 20, carbs: 0, fats: 13 },
  { name: "Tuna Canned in Water", brand: "Generic", servingSize: "100g", calories: 116, protein: 26, carbs: 0, fats: 0.8 },
  { name: "Brown Rice", brand: "Generic", servingSize: "1 cup cooked", calories: 216, protein: 5, carbs: 45, fats: 1.8 },
  { name: "White Rice", brand: "Generic", servingSize: "1 cup cooked", calories: 205, protein: 4.3, carbs: 45, fats: 0.4 },
  { name: "Jasmine Rice", brand: "Generic", servingSize: "1 cup cooked", calories: 238, protein: 4.3, carbs: 45, fats: 0.4 },
  { name: "Basmati Rice", brand: "Generic", servingSize: "1 cup cooked", calories: 191, protein: 4.4, carbs: 39, fats: 0.6 },
  { name: "Wild Rice", brand: "Generic", servingSize: "1 cup cooked", calories: 166, protein: 6.5, carbs: 35, fats: 0.6 },
  { name: "Rolled Oats", brand: "Generic", servingSize: "1/2 cup dry", calories: 150, protein: 5, carbs: 27, fats: 3 },
  { name: "Whole Wheat Bread", brand: "Generic", servingSize: "1 slice", calories: 81, protein: 4, carbs: 14, fats: 1.1 },
  { name: "Sweet Potato", brand: "Generic", servingSize: "1 medium", calories: 112, protein: 2, carbs: 26, fats: 0.1 },
  { name: "White Potato", brand: "Generic", servingSize: "1 medium", calories: 163, protein: 4.3, carbs: 37, fats: 0.2 },
  { name: "Pasta Cooked", brand: "Generic", servingSize: "1 cup", calories: 221, protein: 8.1, carbs: 43, fats: 1.3 },
  { name: "Quinoa Cooked", brand: "Generic", servingSize: "1 cup", calories: 222, protein: 8, carbs: 39, fats: 3.6 },
  { name: "Black Beans Cooked", brand: "Generic", servingSize: "1 cup", calories: 227, protein: 15, carbs: 41, fats: 0.9 },
  { name: "Greek Yogurt", brand: "Fage", servingSize: "170g", calories: 100, protein: 17, carbs: 6, fats: 0.7 },
  { name: "Cottage Cheese", brand: "Generic", servingSize: "1/2 cup", calories: 110, protein: 14, carbs: 3.5, fats: 4.9 },
  { name: "Milk 2%", brand: "Generic", servingSize: "1 cup", calories: 122, protein: 8, carbs: 12, fats: 4.8 },
  { name: "Almond Milk Unsweetened", brand: "Generic", servingSize: "1 cup", calories: 30, protein: 1, carbs: 1, fats: 2.5 },
  { name: "Cheddar Cheese", brand: "Generic", servingSize: "1 oz", calories: 113, protein: 7, carbs: 0.4, fats: 9.3 },
  { name: "Avocado", brand: "Generic", servingSize: "1/2 medium", calories: 160, protein: 2, carbs: 9, fats: 15 },
  { name: "Banana", brand: "Generic", servingSize: "1 medium", calories: 105, protein: 1.3, carbs: 27, fats: 0.4 },
  { name: "Apple", brand: "Generic", servingSize: "1 medium", calories: 95, protein: 0.5, carbs: 25, fats: 0.3 },
  { name: "Broccoli", brand: "Generic", servingSize: "1 cup chopped", calories: 31, protein: 2.6, carbs: 6, fats: 0.3 },
  { name: "Spinach Raw", brand: "Generic", servingSize: "100g", calories: 23, protein: 2.9, carbs: 3.6, fats: 0.4 },
  { name: "Olive Oil", brand: "Generic", servingSize: "1 tbsp", calories: 119, protein: 0, carbs: 0, fats: 13.5 },
  { name: "Butter", brand: "Generic", servingSize: "1 tbsp", calories: 102, protein: 0.1, carbs: 0, fats: 11.5 },
  { name: "Peanut Butter", brand: "Generic", servingSize: "2 tbsp", calories: 188, protein: 8, carbs: 6, fats: 16 },
  { name: "Protein Powder Whey", brand: "Generic", servingSize: "1 scoop ~30g", calories: 120, protein: 24, carbs: 3, fats: 1.5 },
] as const;
